{% set version = "0.8.4" %}
{% set sha256 = "4958a19cbd8461757a08db308a4a15c3d586660417e1e364f0107d2fe481689f" %}

package:
  name: python-graphviz
  version: {{ version }}

source:
  fn: python-graphviz-{{ version }}.zip
  url: https://pypi.io/packages/source/g/graphviz/graphviz-{{ version }}.zip
  sha256: {{ sha256 }}
  patches:
    # needed due to the Windows batch script wrappers in conda-forge Graphviz
    # see https://github.com/conda-forge/graphviz-feedstock/blob/bbfe3c7be2a448dd11db165a18c3edfd5ee6a95d/recipe/bld.bat#L27-L32
    - windows-bat.patch  # [win]

build:
  number: 1002
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - graphviz

test:
  imports:
    - graphviz
  requires:
    - dask

about:
  home: https://github.com/xflr6/graphviz
  doc_url: https://graphviz.readthedocs.io
  dev_url: https://github.com/xflr6/graphviz

  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

  summary: Simple Python interface for Graphviz
  description: |
    This package facilitates the creation and rendering of graph
    descriptions in the DOT language of the Graphviz graph
    drawing software from Python.

extra:
  recipe-maintainers:
    - jakirkham
    - scopatz
