{% set version = "0.6" %}
{% set sha256 = "b4be2b3438971588dc306116658f475916755ad8fcc0618e79023846ce94f97b" %}

package:
  name: python-graphviz
  version: {{ version }}

source:
  fn: python-graphviz-{{ version }}.zip
  url: https://pypi.io/packages/source/g/graphviz/graphviz-{{ version }}.zip
  sha256: {{ sha256 }}
  patches:
    # This is needed because Graphviz binaries (e.g. dot) are redefined as
    # batch scripts in the Graphviz conda-forge package. Hence, it doesn't
    # make sense to submit this patch upstream
    - shell.patch  # [win]

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - graphviz

test:
  imports:
    - graphviz
  requires:
    - dask

about:
  home: http://github.com/xflr6/graphviz
  doc_url: http://graphviz.readthedocs.io
  dev_url: https://github.com/xflr6/graphviz

  license: MIT
  license_family: MIT
  license_file: LICENSE

  summary: Simple Python interface for Graphviz
  description: |
    This package facilitates the creation and rendering of graph
    descriptions in the DOT language of the Graphviz graph
    drawing software (repo) from Python.

extra:
  recipe-maintainers:
    - jakirkham
    - ccordoba12
