{% set version = "0.16" %}
{% set sha256 = "d2d25af1c199cad567ce4806f0449cb74eb30cf451fd7597251e1da099ac6e57" %}

package:
  name: python-graphviz
  version: {{ version }}

source:
  fn: python-graphviz-{{ version }}.zip
  url: https://pypi.io/packages/source/g/graphviz/graphviz-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 2
  noarch: python

requirements:
  build:
    - patch
  host:
    - python
    - pip
  run:
    - python
    - graphviz

test:
  imports:
    - graphviz
  requires:
    - dask

about:
  home: https://github.com/xflr6/graphviz
  doc_url: https://graphviz.readthedocs.io
  dev_url: https://github.com/xflr6/graphviz

  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

  summary: Simple Python interface for Graphviz
  description: |
    This package facilitates the creation and rendering of graph
    descriptions in the DOT language of the Graphviz graph
    drawing software from Python.

extra:
  recipe-maintainers:
    - jakirkham
    - scopatz
