{% set version = "0.18" %}

package:
  name: python-graphviz
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/graphviz/graphviz-{{ version }}.zip
  sha256: 0f04e5f939d3a839b524283d590e941892c56e75e60e0f5238c431264f490022

build:
  number: 0
  noarch: python
  script:
    - python -m pip install --no-deps --ignore-installed "{{ SRC_DIR }}"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - graphviz >=2.46.1

test:
  imports:
    - graphviz
  requires:
    - dask
    - pip
  commands:
    - pip check

about:
  home: https://github.com/xflr6/graphviz
  doc_url: https://graphviz.readthedocs.io
  dev_url: https://github.com/xflr6/graphviz

  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

  summary: Simple Python interface for Graphviz
  description: |
    This package facilitates the creation and rendering of graph
    descriptions in the DOT language of the Graphviz graph
    drawing software from Python.

extra:
  recipe-maintainers:
    - jakirkham
    - scopatz
