{% set version = "0.20.3" %}

package:
  name: python-graphviz
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/graphviz/graphviz-{{ version }}.zip
  sha256: 09d6bc81e6a9fa392e7ba52135a9d49f1ed62526f96499325930e87ca1b5925d

build:
  number: 2
  noarch: python
  script:
    - python -m pip install --no-deps --ignore-installed "{{ SRC_DIR }}"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - graphviz >=2.46.1

test:
  imports:
    - graphviz
  requires:
    - dask
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/xflr6/graphviz
  doc_url: https://graphviz.readthedocs.io
  dev_url: https://github.com/xflr6/graphviz

  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

  summary: Simple Python interface for Graphviz
  description: |
    This package facilitates the creation and rendering of graph
    descriptions in the DOT language of the Graphviz graph
    drawing software from Python.

extra:
  recipe-maintainers:
    - jakirkham
    - scopatz
