{% set version = "0.13.1" %}
{% set sha256 = "ef371ea1ddb1749d5b502324b3f645fa90e208956a4ac6ff29affa944bc4d018" %}

package:
  name: python-graphviz
  version: {{ version }}

source:
  fn: python-graphviz-{{ version }}.zip
  url: https://pypi.io/packages/source/g/graphviz/graphviz-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script:
    # Needed due to the Windows batch script wrappers in conda-forge Graphviz.
    # see https://github.com/conda-forge/graphviz-feedstock/blob/bbfe3c7be2a448dd11db165a18c3edfd5ee6a95d/recipe/bld.bat#L27-L32
    # Must patch manually as the source code and patch are CRLF and conda-build
    # tries to convert the patch to LF, which then won't apply.
    - pushd "{{ RECIPE_DIR }}"
    - cp windows-bat.patch "{{ SRC_DIR }}"
    - popd
    - patch --binary -p0 -i windows-bat.patch
    - python -m pip install --no-deps --ignore-installed "${SRC_DIR}"

requirements:
  build:
    - patch
  host:
    - python
    - pip
  run:
    - python
    - graphviz

test:
  imports:
    - graphviz
  requires:
    - dask

about:
  home: https://github.com/xflr6/graphviz
  doc_url: https://graphviz.readthedocs.io
  dev_url: https://github.com/xflr6/graphviz

  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

  summary: Simple Python interface for Graphviz
  description: |
    This package facilitates the creation and rendering of graph
    descriptions in the DOT language of the Graphviz graph
    drawing software from Python.

extra:
  recipe-maintainers:
    - jakirkham
    - scopatz
